version: '3'

services:
  chat:
    image: ${REGISTRY}/${IMAGE_NAME}:${TAG_NAME}
    env_file:
      - .env
    ports:
      - ${GRPC_PORT}:50052
    networks:
      - dmz
      - ins
    depends_on:
      - chat-pg
      - chat-migrator
  
  chat-pg:
    image: postgres:16-alpine3.19
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./pg-data2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - ins

  chat-migrator:
    image: cr.selcloud.ru/practice/migrator:latest
    env_file:
      - .env
    volumes:
        - ./chat-service/migrations:/go/bin/migrations
    restart: on-failure
    networks:
      - ins
    depends_on:
      - chat-pg


volumes:
  pg-data2:
    
networks:
  dmz:
  ins: